Us15 feedback de erro
fga-eps-mds/2023-2-CAPJu-Unit-Service pull request #16
Opened 2023-12-20 14:38 UTC by LeanArs

## Descrição
Adiciona feedback de erro ao criar ou editar unidade.

## Revisão

- [] Feedback de erro "Nome da unidade já existe. Por favor, escolha um nome diferente" é mostrado ao tentar criar unidade com mesmo nome
- [] Feedback de erro "Essa unidade não existe." é mostrado ao tentar atualizar uma unidade no qual o idUnit não existe
- [] Feedback de erro "Erro ao criar unidade" é mostrado ao falhar ao criar unidade
- [] Feedback de erro "Erro ao atualizar unidade" é mostrado ao falhar ao atualizar unidade

## Pre-merge checklist

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-12-20 17:48 UTC, Denniel-sudo approved these changes

2023-12-20 17:49 UTC, Denniel-sudo requested changes
Pipe quebrada

2023-12-21 01:28 UTC, Denniel-sudo approved these changes

2023-12-21 01:29 UTC, brendavsantos approved these changes

2023-12-21 01:29 UTC, merged